### ISSUE TITLE
Content not valid

### ISSUE THREAD

**Issue by andrei2popa** [aranhil/SearchableNavbar#6]
Hi Stefan-Iulian,

I just discovered and installed your addin. Thank you for sharing it, it should really help the development.
However, in my C# project/solution it allows to navigate only code from a specific namespace and not the one from the current file.
Let me know if I can help you with any details.
![2023_08_15_16_40_49_](https://github.com/aranhil/SearchableNavbar/assets/38735090/8a1d78fd-7bed-485b-9ba7-39e95ddfe253)

Best regards,
Andrei Popa

**Comment by andrei2popa** [comment]
short update: if I close the file and reopen it, it updates the navigator combobox.  meaning, after opening a solution if undocked files exist they will show the content of the file that is part of the VS MainWindow.... hope that helps....

**Comment by andrei2popa** [comment]
well, we are all busy, I think we can live with a such bug :)

**Comment by aranhil** [comment]
I didn't know about this issue, I missed the email.

**Comment by aranhil** [comment]
Fixed with version 1.14
