### ISSUE TITLE
Not support Unreal Engine functions and properties

### ISSUE THREAD

**Issue by zbjxb** [aranhil/SearchableNavbar#7]
Like the screenshot:
![image](https://github.com/aranhil/SearchableNavbar/assets/4047306/bf0cc22e-0124-4c85-b1e7-b9227eff152e)
![image](https://github.com/aranhil/SearchableNavbar/assets/4047306/51b04de1-77a7-4a95-9e28-edcc1f061a1a)

**Comment by aranhil** [comment]
Fixed with version 1.15

**Comment by zbjxb** [comment]
So fast!!!! 👍👍👍😍
